#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# Read inputs
payload=$(mktemp $TMPDIR/helm-resource-request.XXXXXX)
cat > $payload <&0

# Parse parameters
host=$(jq -r '.source.host // "https://sentry.io"' < $payload)
token=$(jq -r '.source.token // ""' < $payload)
organization=$(jq -r '.source.organization // ""' < $payload)
project=$(jq -r '.source.project // ""' < $payload)


curl -s -H "Authorization: Bearer $token" \
    "$host/api/0/projects/$organization/$project/releases/" \
    | jq "map({ \"ref\": .version }) | reverse" >&3
